# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Themis Project
email: reynal@ensea.fr
description: > # this means to ignore newlines until "baseurl:"
  Themis is a hybrid digital-analog music synthetiser that takes the best from both worlds in order to produce the best sound ever.
baseurl: "" # the subpath of your site, e.g. /blog
lang: "en"
url: "http://reynal.github.io/themis/" # the base hostname & protocol for your site
twitter_username: sydxrey
github_username:  reynal
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'
